### ISSUE TITLE
Create or edit a text plugin with CKEditor 4 or 5 fails on error 'value too long'

### ISSUE THREAD

**Issue by sveetch** [django-cms/djangocms-text#46]
## Describe the bug

When trying to create a new text plugin item or editing an existing one from a page
(either Draft or Published) it fails on an error
`Exception Value: value too long for type character varying(16)`

This happening with both CKEditor 4 and 5, but never with Tiptap. However whatever the
editor i define, create a text item from the Page creation wizard does not trigger this
error and content is correctly created.

### Full traceback:

Here is the traceback that is the same for both CKEditor 4 and 5. See below the
*With ...* sections where i've added a paste of debugging pointers i've collected along
the defined settings for each editor i've tried.

```
Traceback (most recent call last):
  File "/home/emencia/Projects/Apps/Cookies-dev/bireli/dist/uranus/.venv/lib/python3.10/site-packages/django/db/backends/utils.py", line 105, in _execute
    return self.cursor.execute(sql, params)

The above exception (value too long for type character varying(16)
) was the direct cause of the following exception:
  File "/home/emencia/Projects/Apps/Cookies-dev/bireli/dist/uranus/.venv/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/emencia/Projects/Apps/Cookies-dev/bireli/dist/uranus/.venv/lib/python3.10/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/emencia/Projects/Apps/Cookies-dev/bireli/dist/uranus/.venv/lib/python3.10/site-packages/django/utils/decorators.py", line 188, in _view_wrapper
    result = _process_exception(request, e)
  File "/home/emencia/Projects/Apps/Cookies-dev/bireli/dist/uranus/.venv/lib/python3.10/site-packages/django/utils/decorators.py", line 186, in _view_wrapper
    response = view_func(request, *args, **kwargs)
  File "/home/emencia/Projects/Apps/Cookies-dev/bireli/dist/uranus/.venv/lib/python3.10/site-packages/django/views/decorators/cache.py", line 80, in _view_wrapper
    response = view_func(request, *args, **kwargs)
  File "/home/emencia/Projects/Apps/Cookies-dev/bireli/dist/uranus/.venv/lib/python3.10/site-packages/django/contrib/admin/sites.py", line 240, in inner
    return view(request, *args, **kwargs)
  File "/home/emencia/Projects/Apps/Cookies-dev/bireli/dist/uranus/.venv/lib/python3.10/site-packages/django/views/decorators/clickjacking.py", line 58, in _view_wrapper
    response = view_func(*args, **kwargs)
  File "/home/emencia/Projects/Apps/Cookies-dev/bireli/dist/uranus/.venv/lib/python3.10/site-packages/cms/admin/placeholderadmin.py", line 610, in edit_plugin
    response = plugin_instance.change_view(request, str(plugin_id))
  File "/home/emencia/Projects/Apps/Cookies-dev/bireli/dist/uranus/.venv/lib/python3.10/site-packages/django/contrib/admin/options.py", line 1950, in change_view
    return self.changeform_view(request, object_id, form_url, extra_context)
  File "/home/emencia/Projects/Apps/Cookies-dev/bireli/dist/uranus/.venv/lib/python3.10/site-packages/django/utils/decorators.py", line 48, in _wrapper
    return bound_method(*args, **kwargs)
  File "/home/emencia/Projects/Apps/Cookies-dev/bireli/dist/uranus/.venv/lib/python3.10/site-packages/django/utils/decorators.py", line 188, in _view_wrapper
    result = _process_exception(request, e)
  File "/home/emencia/Projects/Apps/Cookies-dev/bireli/dist/uranus/.venv/lib/python3.10/site-packages/django/utils/decorators.py", line 186, in _view_wrapper
    response = view_func(request, *args, **kwargs)
  File "/home/emencia/Projects/Apps/Cookies-dev/bireli/dist/uranus/.venv/lib/python3.10/site-packages/django/contrib/admin/options.py", line 1806, in changeform_view
    return self._changeform_view(request, object_id, form_url, extra_context)
  File "/home/emencia/Projects/Apps/Cookies-dev/bireli/dist/uranus/.venv/lib/python3.10/site-packages/django/contrib/admin/options.py", line 1857, in _changeform_view
    self.save_model(request, new_object, form, not add)
  File "/home/emencia/Projects/Apps/Cookies-dev/bireli/dist/uranus/.venv/lib/python3.10/site-packages/djangocms_text/cms_plugins.py", line 716, in save_model
    super().save_model(request, obj, form, change)
  File "/home/emencia/Projects/Apps/Cookies-dev/bireli/dist/uranus/.venv/lib/python3.10/site-packages/cms/plugin_base.py", line 476, in save_model
    self.saved_object = pl.add_plugin(obj)
  File "/home/emencia/Projects/Apps/Cookies-dev/bireli/dist/uranus/.venv/lib/python3.10/site-packages/cms/models/placeholdermodel.py", line 543, in add_plugin
    instance.save()
  File "/home/emencia/Projects/Apps/Cookies-dev/bireli/dist/uranus/.venv/lib/python3.10/site-packages/djangocms_text/models.py", line 80, in save
    super().save(*args, **kwargs)
  File "/home/emencia/Projects/Apps/Cookies-dev/bireli/dist/uranus/.venv/lib/python3.10/site-packages/django/db/models/base.py", line 822, in save
    self.save_base(
  File "/home/emencia/Projects/Apps/Cookies-dev/bireli/dist/uranus/.venv/lib/python3.10/site-packages/django/db/models/base.py", line 909, in save_base
    updated = self._save_table(
  File "/home/emencia/Projects/Apps/Cookies-dev/bireli/dist/uranus/.venv/lib/python3.10/site-packages/django/db/models/base.py", line 1040, in _save_table
    updated = self._do_update(
  File "/home/emencia/Projects/Apps/Cookies-dev/bireli/dist/uranus/.venv/lib/python3.10/site-packages/django/db/models/base.py", line 1105, in _do_update
    return filtered._update(values) > 0
  File "/home/emencia/Projects/Apps/Cookies-dev/bireli/dist/uranus/.venv/lib/python3.10/site-packages/django/db/models/query.py", line 1278, in _update
    return query.get_compiler(self.db).execute_sql(CURSOR)
  File "/home/emencia/Projects/Apps/Cookies-dev/bireli/dist/uranus/.venv/lib/python3.10/site-packages/django/db/models/sql/compiler.py", line 1990, in execute_sql
    cursor = super().execute_sql(result_type)
  File "/home/emencia/Projects/Apps/Cookies-dev/bireli/dist/uranus/.venv/lib/python3.10/site-packages/django/db/models/sql/compiler.py", line 1562, in execute_sql
    cursor.execute(sql, params)
  File "/home/emencia/Projects/Apps/Cookies-dev/bireli/dist/uranus/.venv/lib/python3.10/site-packages/debug_toolbar/panels/sql/tracking.py", line 235, in execute
    return self._record(super().execute, sql, params)
  File "/home/emencia/Projects/Apps/Cookies-dev/bireli/dist/uranus/.venv/lib/python3.10/site-packages/debug_toolbar/panels/sql/tracking.py", line 160, in _record
    return method(sql, params)
  File "/home/emencia/Projects/Apps/Cookies-dev/bireli/dist/uranus/.venv/lib/python3.10/site-packages/django/db/backends/utils.py", line 122, in execute
    return super().execute(sql, params)
  File "/home/emencia/Projects/Apps/Cookies-dev/bireli/dist/uranus/.venv/lib/python3.10/site-packages/django/db/backends/utils.py", line 79, in execute
    return self._execute_with_wrappers(
  File "/home/emencia/Projects/Apps/Cookies-dev/bireli/dist/uranus/.venv/lib/python3.10/site-packages/django/db/backends/utils.py", line 92, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "/home/emencia/Projects/Apps/Cookies-dev/bireli/dist/uranus/.venv/lib/python3.10/site-packages/django/db/backends/utils.py", line 100, in _execute
    with self.db.wrap_database_errors:
  File "/home/emencia/Projects/Apps/Cookies-dev/bireli/dist/uranus/.venv/lib/python3.10/site-packages/django/db/utils.py", line 91, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/home/emencia/Projects/Apps/Cookies-dev/bireli/dist/uranus/.venv/lib/python3.10/site-packages/django/db/backends/utils.py", line 105, in _execute
    return self.cursor.execute(sql, params)

Exception Type: DataError at /admin/cms/placeholder/edit-plugin/4/
Exception Value: value too long for type character varying(16)
```

### With CKEditor 4

**With the following settings**

```
INSTALLED_APPS.extend([
    "djangocms_text",
    "djangocms_text.contrib.text_ckeditor4",
])

TEXT_EDITOR = "djangocms_text.contrib.text_ckeditor4.ckeditor4"
```

**Custom bug debugging pointers**

```
🐛 Line 427: From editors.get_editor_config():
   └─ Line 435: TEXT_EDITOR: djangocms_text.contrib.text_ckeditor4.ckeditor4
   └─ Line 436: config: djangocms_text.contrib.text_ckeditor4.ckeditor4
   └─ Line 437: Entering condition for uncached config with dotted path
      └─ Line 440: config.rsplit: ckeditor4
      └─ Line 440: rte_config_instance: <djangocms_text.editors.RTEConfig object at 0x7fef552e61d0>
      └─ Line 442: rte_config_instance.name: djangocms_text.contrib.text_ckeditor4.ckeditor4

🐛 Line 77: AbstractText.save:
   └─ Line 78: self.rte: djangocms_text.contrib.text_ckeditor4.ckeditor4
   └─ Line 78: rte length: 47
```

### With CKEditor 5

**With the following settings**

```
INSTALLED_APPS.extend([
    "djangocms_text",
    "djangocms_text_ckeditor5",
])

TEXT_EDITOR = "djangocms_text_ckeditor5.ckeditor5"
```

**Custom bug debugging pointers**

```
🐛 Line 427: From editors.get_editor_config():
   └─ Line 435: TEXT_EDITOR: djangocms_text_ckeditor5.ckeditor5
   └─ Line 436: config: djangocms_text_ckeditor5.ckeditor5
   └─ Line 437: Uncached config with dotted path
      └─ Line 440: config.rsplit: ckeditor5
      └─ Line 440: rte_config_instance: <djangocms_text.editors.RTEConfig object at 0x7f375c2ba140>
      └─ Line 442: rte_config_instance.name: djangocms_text_ckeditor5.ckeditor5

🐛 Line 77: AbstractText.save:
   └─ Line 78: self.rte: djangocms_text_ckeditor5.ckeditor5
   └─ Line 78: rte length: 34
```

### With TipTap

**With the following settings**

```
INSTALLED_APPS.extend([
    "djangocms_text",
])
```

**Custom bug debugging pointers**

```
🐛 Line 427: From editors.get_editor_config():
   └─ Line 435: TEXT_EDITOR: tiptap
   └─ Line 436: config: tiptap

🐛 Line 77: AbstractText.save:
   └─ Line 78: self.rte: tiptap
   └─ Line 78: rte length: 6
```

## Environment

Describe your environment:

- Plateform: Linux distribution
- Python version: 3.10.7
- Django version: 5.0.10
- DjangoCMS version: 4.1.4
- djangocms-text version: 0.3.3, 0.4.0

## Additional context

As seen from error and debug pointer the editor name for CKEditors is clearly too long
for the max size of the 'rte' field because they are the full Python module path,
opposed to TipTag that is just the *tiptap* name.

However i'm very confused because i did not seen this bug from the past two weeks i
worked with djangocms-text, did i miss a thing in my settings or something else ?

First i was still with djangocms-text v0.3.3 but then after i've updated to the v0.4.0
and the bug is still there with exactly the same behaviors. 

Note that my bug debugging pointers pastes reference to the code line from the v0.3.3.

**Comment by fsbraun** [comment]
@sveetch Thanks, great catch! The integration test did check if the ckeditor4 started up, but did not check save. Not the whole path should go into the DB field, just the final editor name. Fix is coming up.
